# markdown: redcarpet2
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
markdown: redcarpet
pygments: true
auto: true

name: Sparrow-Labs Development Blog
description: The Sparrow-Labs Development Blog.
url: http://sparrow-labs.github.io
# url: http://blog.sparrow-labs.de

